### PR TITLE
Update badges

### PR DESCRIPTION
**Pull request by hlaueriksson**
The build badges are broken. Change AppVeyor to GitHub Actions.

### CODE REVIEW

**Comment by hlaueriksson** [comment]
The Ping me on `xs:code` badge is also broken.

@kblok Would you like to have a Open Collective badge instead?

**Comment by kblok** [comment]
Thank you @hlaueriksson. I don't even remember what xs:code is 😂 .
Let's remove it. We have sponsors links at the right of the github page.

**Comment by hlaueriksson** [comment]
After googling I found that xs:code was

> a monetization platform for open source projects

It's removed now.

**Comment by hlaueriksson** [comment]
image

If you want to change the display name of `Demo Project`, you can rename the workflow:

https://github.com/hardkoded/puppeteer-sharp/blob/ce082ee684da40903e819d4224225098863832ce/.github/workflows/demo.yml#L1

**Pull request merged**
