### PR TITLE
enable CA1032 rule and implement standard exception constructors

### PR DESCRIPTION
**Pull request by qtuu**
fixes issue #1425

### CODE REVIEW

**Comment by qtuu** [comment]
could you please add the hacktoberfest-accepted label to this PR, so it gets counted towards my progress? :)

**Comment by qtuu** [comment]
Can i improve anything @kblok ?

**Comment by kblok** [comment]
Looking good! 
I will merge it tomorrow 😊

**Comment by qtuu** [comment]
Could you add the hacktoberfest-accepted label, please? ;)

**Comment by kblok** [comment]
Done @qtuu  :)

**Comment by qtuu** [comment]
Thank you ☺️

**Pull request merged**
