### PR TITLE
RAM Leak Fix

### PR DESCRIPTION
**Pull request by Mephisto090**

### CODE REVIEW

**Comment by Mephisto090** [comment]
Only Add-Line 28

**Comment by kblok** [comment]
Can you fix the line endings to restore them to the original ones?

**Comment by Mephisto090** [comment]
Can you just paste the line or accept this pull request? Otherwise I would have to do everything via Visual Studio and post a new request.

**Comment by Mephisto090** [comment]
Underway give me 10min :)

**Pull request closed without merging**
