### PR TITLE
Improve DOMWorld initialization

### LINKED ISSUE #1670: Object reference not set to an instance of an object
```
PuppeteerSharp.NavigationException: Navigation failed because browser has disconnected! (Connection failed to process Runtime.executionContextCreated. Object reference not set to an instance of an object..
    at PuppeteerSharp.DOMWorld.SetContext(ExecutionContext context) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 37
    at PuppeteerSharp.FrameManager.OnExecutionContextCreatedAsync(ContextPayload contextPayload) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 291
    at PuppeteerSharp.FrameManager.Client_MessageReceived(Object sender, MessageEventArgs e) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 218)
 ---> PuppeteerSharp.TargetClosedException: Navigation failed because browser has disconnected! (Connection failed to process Runtime.executionContextCreated. Object reference not set to an instance of an object..
    at PuppeteerSharp.DOMWorld.SetContext(ExecutionContext context) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 37
    at PuppeteerSharp.FrameManager.OnExecutionContextCreatedAsync(ContextPayload contextPayload) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 291
    at PuppeteerSharp.FrameManager.Client_MessageReceived(Object sender, MessageEventArgs e) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 218)
   at PuppeteerSharp.Helpers.TaskHelper.WithTimeout(Task task, Func`1 timeoutAction, TimeSpan timeout, CancellationToken cancellationToken) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Helpers\TaskHelper.cs:line 82
   at PuppeteerSharp.FrameManager.NavigateFrameAsync(Frame frame, String url, NavigationOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 130
   --- End of inner exception stack trace ---
```

```
PuppeteerSharp.NavigationException: Protocol error (Page.navigate): Session closed. Most likely the Page has been closed.Close reason: Connection failed to process Runtime.executionContextCreated. Object reference not set to an instance of an object..
    at PuppeteerSharp.DOMWorld.SetContext(ExecutionContext context) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 37
    at PuppeteerSharp.FrameManager.OnExecutionContextCreatedAsync(ContextPayload contextPayload) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 291
    at PuppeteerSharp.FrameManager.Client_MessageReceived(Object sender, MessageEventArgs e) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 218
 ---> PuppeteerSharp.PuppeteerException: Protocol error (Page.navigate): Session closed. Most likely the Page has been closed.Close reason: Connection failed to process Runtime.executionContextCreated. Object reference not set to an instance of an object..
    at PuppeteerSharp.DOMWorld.SetContext(ExecutionContext context) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 37
    at PuppeteerSharp.FrameManager.OnExecutionContextCreatedAsync(ContextPayload contextPayload) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 291
    at PuppeteerSharp.FrameManager.Client_MessageReceived(Object sender, MessageEventArgs e) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 218
   at PuppeteerSharp.CDPSession.SendAsync(String method, Object args, Boolean waitForCallback) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CDPSession.cs:line 157
   at PuppeteerSharp.CDPSession.SendAsync[T](String method, Object args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CDPSession.cs:line 109
   at PuppeteerSharp.FrameManager.NavigateAsync(CDPSession client, String url, String referrer, String frameId) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 147
   at PuppeteerSharp.FrameManager.NavigateFrameAsync(Frame frame, String url, NavigationOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 130
   --- End of inner exception stack trace ---
```

https://github.com/hardkoded/puppeteer-sharp/blob/8262c805fc32a63cb3390d71a26260c2c5224013/lib/PuppeteerSharp/DOMWorld.cs#L39

https://github.com/puppeteer/puppeteer/blob/b349c91e7df76630b7411d6645e649945c4609bd/src/common/DOMWorld.ts#L119

See upstream issue https://github.com/puppeteer/puppeteer/issues/4197

### PR DESCRIPTION
**Pull request by kblok**
closes #1670

### CODE REVIEW

**Comment by kblok** [comment]
Check this out @Androbin. By initializing the properties we don't need to call `SetContext` in the constructor, and there wouldn't be any chance of a null TaskCompletionSource.

**Comment by Androbin** [comment]
I would like to think this is equivalent to the current version.

**Comment by Androbin** [comment]
```
World world = null
```

Thread 1:
```
world = new DOMWorld(...);
```

- `DOMWorld` is allocated
- `TaskCompletionSource<ExecutionContext>` is allocated
- `_contextResolveTaskWrapper` is assigned
- `world` is assigned

Thread 2:
```
world?.SetContext(new ExecutionContext(...));
```

**Comment by Androbin** [comment]
Thread 2 simply cannot observe `world != null` before `_contextResolveTaskWrapper` is assigned

**Comment by kblok** [comment]
@Androbin true.

**Pull request closed without merging**
