### PR TITLE
change SA1600 rulset to Error

### PR DESCRIPTION
**Pull request by MajeQafouri**
Reference Issue: https://github.com/hardkoded/puppeteer-sharp/issues/1384

### CODE REVIEW

**Comment by kblok** [comment]
@MajeQafouri did you miss any commit here?

**Comment by kblok** [comment]
@MajeQafouri these issues are about enabling that rule and fixing the errors that come from enabling it.

**Comment by MajeQafouri** [comment]
> @MajeQafouri these issues are about enabling that rule and fixing the errors that come from enabling it.

Ok, I will check it again

**Comment by MajeQafouri** [comment]
@kblok 
During the build process, StyleCop.Analyzers package does not allow to build the solution, because of the lack of documentation. do you have any suggestions?

**Comment by kblok** [comment]
If SA1600 wasn't set as an error before it's because we have missing documentation :)
I see that much of the missing documentation is from internal elements. I would try disabling that using [this](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md#documentation-requirements).
After that, we will need to add all the missing documentation. Constructors tend to have the same style, the same for exceptions. [pptr.dev](https://pptr.dev/) is a good source of content.

**Comment by MajeQafouri** [comment]
>

**Pull request closed without merging**
