### PR TITLE
fix(requestinterception): fix font loading issue

### LINKED ISSUE #1185: Cache is force disabled when intercept requests
### Description
if i use`await page.SetRequestInterceptionAsync(true);` , cache is force disabled(at least images is not caching). But I just want to intercept xhr requests not any request. Any method to enable caching while intercept requests?

### PR DESCRIPTION
**Pull request by Androbin**
See upstream: https://github.com/puppeteer/puppeteer/pull/7060

Fixes #1185

### CODE REVIEW

**Comment by kblok** [comment]
Nice job upstream @Androbin!

**Comment by kblok** [comment]
Can you check the builds here?

**Comment by kblok** [comment]
I think we are getting consistent fails here @Androbin

**Comment by Androbin** [comment]
This change is needed to fix #1185 but it breaks the `ShouldProperlyReturnNavigationResponseWhenURLHasCookies` test. The same test was unaffected in upstream JavaScript Puppeteer.
```diff
 private Task UpdateProtocolCacheDisabledAsync()
     => _client.SendAsync("Network.setCacheDisabled", new NetworkSetCacheDisabledRequest
     {
-        CacheDisabled = _userCacheDisabled || _userRequestInterceptionEnabled
+        CacheDisabled = _userCacheDisabled
     });
```

**Comment by Androbin** [comment]
@kblok This PR is ready to merge, let's find out what's keeping us from re-enabling the cache in another ticket.

**Comment by Androbin** [comment]
Maybe the issue is just that `PuppeteerSharp.TestServer` doesn't honor cookies properly

**Comment by Androbin** [comment]
The `PuppeteerLaunchTests.ShouldWorkWithNoDefaultArguments` test is unrelated and failing on `master` branch as well.

**Review by kblok — APPROVED** [review]
Thank you for all the hard work!

**Pull request merged**
