### PR TITLE
Enabled and fixed errors for SA1009

### PR DESCRIPTION
**Pull request by kongory**
[#1396 ](https://github.com/hardkoded/puppeteer-sharp/issues/1396)

### CODE REVIEW

**Comment by kblok** [comment]
Waiting on this one. I think it will get conflicted with #1560

**Comment by konstantin-gorbachev-Simpligov** [comment]
> Waiting on this one. I think it will get conflicted with #1560

Ok. I also will wait for the mentioned PR is merged to fix conflicts if needed.

**Comment by kblok** [comment]
Conflicted here @kongory

**Comment by kblok** [comment]
Thanks!

**Pull request merged**
