### PR TITLE
Enable rule SA1629

### LINKED ISSUE #1386: Enable SA1629 rule
Change the action for SA1629 on the [ruleset file](https://github.com/kblok/puppeteer-sharp/blob/master/lib/PuppeteerSharp.ruleset) to Error, and make the solution build

### PR DESCRIPTION
**Pull request by akshay-zz**
Fix #1386

### CODE REVIEW

**Review by kblok — APPROVED** [review]
Thank you!

**Comment by kblok** [comment]
@akshay-zz Could you resolve the conflicts?

**Comment by akshay-zz** [comment]
> @akshay-zz Could you resolve the conflicts?

I have rebased the branch after pulling the latest master changes. Really confused why PR is showing differences from older commits. Although I have compared it with the latest master branch there is no difference other than changes related to SA1629. @kblok

**Comment by kblok** [comment]
@akshay-zz It seems the rebase was based on an old master branch. Fixed it :)

**Pull request merged**
