### PR TITLE
Fix MultiMap concurrency issues

### PR DESCRIPTION
**Pull request by Androbin**
I have prepared a test project to demonstrate the errors that can occur with the current version: [Test.zip](https://github.com/hardkoded/puppeteer-sharp/files/6256236/Test.zip)
- `Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index`
- `Has` returns wrong value
- (Iterator skips values)

See #1680 for context

### CODE REVIEW

**Comment by Androbin** [comment]
@kblok PTAL

**Comment by kblok** [comment]
@Androbin trying to get firefox tests back. I'll get back here.

**Comment by kblok** [comment]
Same questions here. I don't want to re-invent the wheel.

**Comment by Androbin** [comment]
`ConcurrentBag` doesn't allow you to remove specific elements.

**Comment by Androbin** [comment]
We could make a `ConcurrentDictionary` of locks and do the synchronization in `MultiMapUnsafe` directly.

**Comment by kblok** [comment]
Why didn't we use the same approach as the other PR?

**Comment by Androbin** [comment]
@kblok Done

**Comment by Androbin** [comment]
Fluke? https://ci.appveyor.com/project/kblok/puppeteer-sharp/builds/38604027/job/y0x62ev4jhgqr20k/tests

**Pull request merged**
