### PR TITLE
show md snippets usage

### PR DESCRIPTION
**Pull request by SimonCropp**
replaces by https://github.com/hardkoded/puppeteer-sharp/pull/1668

### CODE REVIEW

**Comment by kblok** [comment]
That's a pretty cool idea. I love it. Although using regions for that feels odd. But I get the point.

**Comment by kblok** [comment]
Don't we need to set up anything to make that action work?

**Comment by SimonCropp** [comment]
u can use comments to delimitate snippets. that is what is used in other languages. but regions give u a enforced start and end. and u can set them to always expand

the action should need no other changes

**Comment by SimonCropp** [comment]
thoughts on this one?

**Comment by kblok** [comment]
I'm trying to wrap v3. I will get back to this after v3 and v8 plan.

**Comment by kblok** [comment]
This would be ready to go once unconflicted @SimonCropp

**Comment by SimonCropp** [comment]
repalced by https://github.com/hardkoded/puppeteer-sharp/pull/1668

**Pull request closed without merging**
