### PR TITLE
Don't disable cache for auth challenge

### PR DESCRIPTION
**Pull request by Androbin**
See https://github.com/puppeteer/puppeteer/pull/6962

### CODE REVIEW

**Comment by kblok** [comment]
It seems that the project is not building

**Comment by Androbin** [comment]
@kblok I added the missing assembly references

**Comment by Androbin** [comment]
The upstream PR got merged

**Comment by kblok** [comment]
Great job on both sides @Androbin!!!

**Comment by Androbin** [comment]
@kblok Do you have any projections when there will be a new release?

**Comment by kblok** [comment]
I'm close here https://github.com/hardkoded/puppeteer-sharp/pull/1640
That will give us PuppeteerSharp 3. Hopefully this week.

**Comment by kblok** [comment]
@Androbin do you have spare time to implement the network emulation feature?

**Comment by Androbin** [comment]
@kblok Are you referring to "network interception" as referred to in https://github.com/puppeteer/puppeteer/issues/2905#issuecomment-406128495?

**Comment by kblok** [comment]
@Androbin  this https://github.com/puppeteer/puppeteer/pull/6759 :)

**Comment by Androbin** [comment]
Yea, I think I can do that. I will get right to it.

**Comment by Androbin** [comment]
Do you keep track of (approximately) which upstream commit this project is up to date with?

**Comment by kblok** [comment]
I will write a post about the state of puppeteer when I release v3. In a few bullets:
 * We are close to v2.1.1
 * But I'm updating the Chromium revision to the one used in pptr v8. Luckily we are fully compatible with that revision.
 * We will be v3 because I'm changing a few datatypes due to Firefox.

Once we get to v3, I'll create a project to get us straight to v8. That will mean:
 * Having a tool to tells us what are the tests we are missing.
 * Once we have that tool we will know the issues we need to create to take us to v8.

That being said. I would love to keep this project moving, but my time is limited. If you want to jump in and contribute, you will be more than welcome :)

**Comment by Androbin** [comment]
I love a good plan

**Pull request merged**
