### PR TITLE
TaskQueue - Make class sealed and simplify Dispose

### PR DESCRIPTION
**Pull request by amaitland**
The class is now **sealed** which means we can remove the `protected` methods

### CODE REVIEW

**Comment by amaitland** [comment]
@kblok What do you think about making `TaskQueue` sealed? The `Dispose/DisposeAsync` code could be greatly simplified.

**Comment by amaitland** [comment]
I've updated the code to make the class `sealed`. I haven't run the tests locally yet.

**Review by kblok — APPROVED** [review]

**Comment by jnyrup** [comment]
Do any of you know why we we call `_ = Task.Run(() => DisposeAsync());` instead of `_semaphore.Wait();`?
I can't find anything about it in #1826.


Also I guess we should also check `_isDisposed` in `DisposeAsync()`

**Comment by amaitland** [comment]
> Do any of you know why we we call `_ = Task.Run(() => DisposeAsync());` instead of `_semaphore.Wait();`?

I wasn't involved in the original implementation. 

Changing to `Wait()` would mean `Dispose` would then block, I'm not sure if that would have any side effects, so I left it alone for now.

> Also I guess we should also check `_isDisposed` in `DisposeAsync()`

I was planning on revisiting this one, the question I have is do we need a `Thread Safe` guard or not? From a quick look at the usage it's probably fine for just a bool check, I'm still somewhat leaning towards using `Interlocked.Exchange`.

```c#
private int _disposed;

public async ValueTask DisposeAsync()
{
    if (Interlocked.Exchange(ref _disposed, 1) != 0)
    {
        return;
    }

    try
    {
        await _semaphore.WaitAsync().ConfigureAwait(false);
    }
    catch (ObjectDisposedException)
    {
        // Ignore
    }

    _semaphore.Dispose();
}
```

**Comment by amaitland** [comment]
> I'm still somewhat leaning towards using `Interlocked.Exchange`.

Promised change as a commit https://github.com/amaitland/puppeteer-sharp/commit/2ca28aa75cb1d59d5e481d881d82afece9e6927c

**Comment by kblok** [comment]
@amaitland @jnyrup Honestly, I never find issues around de disposable path as you are working on.
I did work on many things around page creation, requests lists, etc, etc.
So, as you can see :),  I'm open to suggestions and ideas here.

**Pull request merged**
