### PR TITLE
Set CA2213 rule to Error

### LINKED ISSUE #1441: Enable CA2213 rule
Change the action for CA2213 on the [ruleset file](https://github.com/kblok/puppeteer-sharp/blob/master/lib/PuppeteerSharp.ruleset) to Error, and make the solution build

### PR DESCRIPTION
**Pull request by bananbe**
Set CA2213 rule to Error and adjusted code to this change.

Fixes #1441

### CODE REVIEW

**Comment by kblok** [comment]
Thank you @bananbe!

**Comment by bananbe** [comment]
There's one issue with this rule - it's not passing in [https://github.com/hardkoded/puppeteer-sharp/blob/master/lib/PuppeteerSharp/Transport/WebSocketTransport.cs](url), becuase `Dispose` it's not called on `_readerCancellationSource`. 

In fact it is done in `StopReading()` method, but `Cancel()` and `Dispose()` is called on `readerCts`, which contains `_readerCancellationSource`, so the rule is fulfilled, but not directly.

Do you some suggestions for that?

**Comment by kblok** [comment]
@bananbe it doesn't make any sense. The code is right. Can we ignore the rule in that line?

**Comment by kblok** [comment]
@bananbe We are getting a code style error we just merged. Could you pull from master a build again?

Thanks :)

**Comment by bananbe** [comment]
Sure, I will do that 👍

**Comment by bananbe** [comment]
@kblok One test failed because of timeout. I ran them locally and all, including the one which failed, are passing. Is it something specific to environment, that this is happend? Or this one is failing at random from time to time?

**Comment by kblok** [comment]
@bananbe yeah, I'm running the builds again ;)

**Comment by kblok** [comment]
Thanks!

**Pull request merged**
